from CodeGenrator import Code

maininput = input("Enter or paste the code here to get the word\n")

maininput = maininput.replace(Code.a , "a")
maininput = maininput.replace(Code.b , "b")
maininput = maininput.replace(Code.c , "c")
maininput = maininput.replace(Code.d , "d")
maininput = maininput.replace(Code.e , "e")
maininput = maininput.replace(Code.f , "f")
maininput = maininput.replace(Code.g , "g")
maininput = maininput.replace(Code.h , "h")
maininput = maininput.replace(Code.i , "i")
maininput = maininput.replace(Code.j , "j")
maininput = maininput.replace(Code.k , "k")
maininput = maininput.replace(Code.l , "l")
maininput = maininput.replace(Code.m , "m")
maininput = maininput.replace(Code.n , "n")
maininput = maininput.replace(Code.o , "o")
maininput = maininput.replace(Code.p , "p")
maininput = maininput.replace(Code.q , "q")
maininput = maininput.replace(Code.r , "r")
maininput = maininput.replace(Code.s , "s")
maininput = maininput.replace(Code.t , "t")
maininput = maininput.replace(Code.u , "u")
maininput = maininput.replace(Code.v , "v")
maininput = maininput.replace(Code.w , "w")
maininput = maininput.replace(Code.x , "x")
maininput = maininput.replace(Code.y , "y")
maininput = maininput.replace(Code.z , "z")

print(maininput)