class Code:
    codeFormat= "Phone number code"
    a="2(1)"
    b="2(2)"
    c="2(3)"
    d="3(1)"
    e="3(2)"
    f="3(3)"
    g="4(1)"
    h="4(2)"
    i="4(3)"
    j="5(1)"
    k="5(2)"
    l="5(3)"
    m="6(1)"
    n="6(2)"
    o="6(3)"
    p="7(1)"
    q="7(2)"
    r="7(3)"
    s="7(4)"
    t="8(1)"
    u="8(2)"
    v="8(3)"
    w="9(1)"
    x="9(2)"
    y="9(3)"
    z="9(4)"

maininput = input("Enter the word to traanslate to code\n")

maininput = maininput.replace("a" , Code.a)
maininput = maininput.replace("b" , Code.b)
maininput = maininput.replace("c" , Code.c)
maininput = maininput.replace("d" , Code.d)
maininput = maininput.replace("e" , Code.e)
maininput = maininput.replace("f" , Code.f)
maininput = maininput.replace("g" , Code.g)
maininput = maininput.replace("h" , Code.h)
maininput = maininput.replace("i" , Code.i)
maininput = maininput.replace("j" , Code.j)
maininput = maininput.replace("k" , Code.k)
maininput = maininput.replace("l" , Code.l)
maininput = maininput.replace("m" , Code.m)
maininput = maininput.replace("n" , Code.n)
maininput = maininput.replace("o" , Code.o)
maininput = maininput.replace("p" , Code.p)
maininput = maininput.replace("q" , Code.q)
maininput = maininput.replace("r" , Code.r)
maininput = maininput.replace("s" , Code.s)
maininput = maininput.replace("t" , Code.t)
maininput = maininput.replace("u" , Code.u)
maininput = maininput.replace("v" , Code.v)
maininput = maininput.replace("w" , Code.w)
maininput = maininput.replace("x" , Code.x)
maininput = maininput.replace("y" , Code.y)
maininput = maininput.replace("z" , Code.z)

print(maininput)